name: ${service.name}
replicas: ${serviceVariable.replicas}

image: ${artifact.metadata.image}
dockercfg: ${artifact.source.dockerconfig}

test_endpoint: "http://34.122.122.65:80"

workflow_var1: ${workflow.variables.var1}
workflow_var2: ${workflow.variables.var2}

createNamespace: true
namespace: ${infra.kubernetes.namespace}

# Service Type allow you to specify what kind of service you want.
# Possible values for ServiceType are:
# ClusterIP | NodePort | LoadBalancer | ExternalName
serviceType: LoadBalancer

# A Service can map an incoming port to any targetPort.
# targetPort is where application is listening on inside the container.
servicePort: 80
serviceTargetPort: 80

# Specify all environment variables to be added to the container.
# The following two maps, config and secrets, are put into a ConfigMap
# and a Secret, respectively.
# Both are added to the container environment in podSpec as envFrom source.
#env:
#  config:
#    key1: value1
#  secrets:
#    key2: value2