# harness.io/skip-file-for-deploy

apiVersion: v1
kind: Service
metadata:
  name: load-tester-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  #selector:
  #  app: {{.Values.name}}