# harness.io/skip-file-for-deploy

apiVersion: v1
kind: ConfigMap
metadata:
  name: mdpo-trigger-vars
data:
  # property-like keys; each key maps to a simple value
  workflow_var1: 1
  #{{ .Values.workflow_var1 }}
  workflow_var2: 2
  #{{ .Values.workflow_var2 }}

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true    