# harness.io/skip-file-for-deploy

apiVersion: batch/v1
kind: Job
metadata:
  name: load-testing-{{.Values.name}}
spec:
#  ttlSecondsAfterFinished: 10
  parallelism: 3
  template:
    spec:
      containers:
      - name: load-tester
        image: bunchjesse/loadtest:latest
        env:
          - name: DURATION
            value: "1020"
          - name: NUM_USERS
            value: "100"
          - name: REQUESTS_PER_SECOND
            value: "2000"
          - name: URL
            value:  {{.Values.test_endpoint | quote}}
      restartPolicy: Never
  backoffLimit: 4