apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
  replicas: {{int .Values.replicas}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        ports:
        - containerPort: 80
        resources:
          limits:
#            cpu: "25m"
