harnessApiVersion: '1.0'
type: INFRA_DEFINITION
cloudProviderType: KUBERNETES_CLUSTER
deploymentType: KUBERNETES
infrastructure:
- type: DIRECT_KUBERNETES
  cloudProviderName: Harness SE Cluster
  namespace: prod-traffic-tester
  releaseName: release-${infra.kubernetes.infraId}
scopedServices:
- load-tester
