apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.name}}
spec:
  parallelism: {{.Values.load_intensity}}
#  selector:
#    matchLabels:
#      app: {{.Values.name}}
  ttlSecondsAfterFinished: 10
  template:
    #metadata:
    #  labels:
    #    app: {{.Values.name}}
    spec:
      containers:
      - name: load-tester
        image: bunchjesse/loadtest:latest
        #command:
        #  - loadtest
        env:
          - name: DURATION
            value: "40000"
          - name: NUM_USERS
            value: "100"
          - name: REQUESTS_PER_SECOND
            value: "2000"
          - name: URL
            value:  {{.Values.test_endpoint | quote}}
      restartPolicy: Never
  backoffLimit: 4