harnessApiVersion: '1.0'
type: MULTI_SERVICE
concurrencyStrategy: INFRA
envName: Staging Env
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - Ka0gfWh2RIWzrhNYlW5EmQ
phases:
- type: KUBERNETES
  computeProviderName: Harness SE Cluster
  daemonSet: false
  infraDefinitionName: se-cluster-deployer
  name: Canary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    steps:
    - type: K8S_DELETE
      name: Canary Delete
      properties:
        instanceUnitType: COUNT
        resources: ${k8s.canaryWorkload}
    stepsInParallel: false
  provisionNodes: false
  serviceName: nginx-replicated
  statefulSet: false
rollbackPhases:
- type: KUBERNETES
  computeProviderName: Harness SE Cluster
  daemonSet: false
  infraDefinitionName: se-cluster-deployer
  name: Rollback Canary
  phaseNameForRollback: Canary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: nginx-replicated
  statefulSet: false
templatized: true
userVariables:
- type: TEXT
  fixed: false
  mandatory: true
  name: var1
- type: TEXT
  fixed: false
  mandatory: true
  name: var2
