harnessApiVersion: '1.0'
type: MULTI_SERVICE
concurrencyStrategy: INFRA
envName: Staging Env
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - Ka0gfWh2RIWzrhNYlW5EmQ
templatized: false
